### ISSUE TITLE
issue: cnvd爬虫抓取失败返回521错误

### ISSUE THREAD

**Issue by LS95** [Mr-xn/threat-broadcast#12]
[WARNING] : 获取 [CNVD] 威胁情报失败： [HTTP Error 521]

也可以到html页面看到 cnvd的数据好久没有更新了

**Comment by Mr-xn** [comment]
好的 找时间更新下 加速乐的反爬

**Comment by Mr-xn** [comment]
已经更新 cnvd 爬虫，明天更新应该就可以收到了，为了保护目标站点没有太大压力，暂时不公开网址
