### ISSUE TITLE
为什么邮箱接收到两个源邮箱的推送

### ISSUE THREAD

**Issue by swordtalk** [Mr-xn/threat-broadcast#14]
为什么邮箱接收到两个源邮箱的推送 #13 除mrxn.net@outlook.com外，还有一个956327636@qq.com

**Comment by Mr-xn** [comment]
> 为什么邮箱接收到两个源邮箱的推送 #13 除[mrxn.net@outlook.com](mailto:mrxn.net@outlook.com)外，还有一个[956327636@qq.com](mailto:956327636@qq.com)

这个邮箱应该是别人克隆过项目 我也收到过两次 可以拉黑或者发邮件告诉他
