### ISSUE TITLE
优化邮件发送格式

### ISSUE THREAD

**Issue by Xc1Ym** [Mr-xn/threat-broadcast#23]
从actions日志来看，该漏洞披露时间和相关链接存在错误
![image](https://user-images.githubusercontent.com/29765332/134291412-64d80009-6ed0-47df-b74d-7622d6f617a8.png)

同时，在使用actions提交到git仓库时，显示未配置用户名
![image](https://user-images.githubusercontent.com/29765332/134292554-e738e6a2-63b5-456a-884f-6d73c33406a4.png)

**Comment by Mr-xn** [comment]
> 从actions日志来看，该漏洞披露时间和相关链接存在错误
> ![image](https://user-images.githubusercontent.com/29765332/134291412-64d80009-6ed0-47df-b74d-7622d6f617a8.png)
> 
> 同时，在使用actions提交到git仓库时，显示未配置用户名
> ![image](https://user-images.githubusercontent.com/29765332/134292554-e738e6a2-63b5-456a-884f-6d73c33406a4.png)

这应该是自己 fork 后的结果，你可以看看我的邮件是正常的，你 fork 后的代码 没有更新
