### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adminlove520** [Mr-xn/threat-broadcast#53]
请问
CRAWL_URL: 
    URL_LIST: 
    URL_CVE: 
这三个参数如何配置？.env嘛或者有范例嘛？本地部署，
![微信图片_20220902203748](https://user-images.githubusercontent.com/32920883/188145630-1bdf31ee-551a-4f43-a87a-85e42f20a254.jpg)

**Comment by Mr-xn** [comment]
参考 https://github.com/lyy289065406/threat-broadcast
